---
# yamllint configuration for TestResults
# This configuration defines the rules for YAML file linting

extends: default

rules:
  # Allow 'on:' in GitHub Actions workflows (not a boolean value)
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: true

  # Allow longer lines for URLs and complex expressions
  line-length:
    max: 120
    level: error

  # Ensure proper indentation
  indentation:
    spaces: 2
    indent-sequences: true

  # Ensure proper comment formatting
  comments:
    min-spaces-from-content: 2

  # Document start is optional
  document-start: disable

  # Allow trailing spaces
  trailing-spaces: disable

  # Allow comments at various indentation levels
  comments-indentation: disable

# Ignore spdx-workflow.yaml as it's not a standard YAML workflow but a custom workflow format
ignore: |
  spdx-workflow.yaml
