---
# TestResults Library Requirements
#
# This file defines the requirements for the TestResults library.
# Requirements are verified through tests and documented in the requirements and trace matrix documents.

sections:
  - title: "TestResults Library Requirements"
    sections:
      - title: "Functional Requirements"
        requirements:
          - id: "REQ-FUNC-001"
            title: "The library shall support creating test result files in TRX (Visual Studio Test Results) format."
            tests:
              - "TrxTests"

          - id: "REQ-FUNC-002"
            title: "The library shall support creating test result files in JUnit XML format."
            tests:
              - "JUnitTests"

          - id: "REQ-FUNC-003"
            title: "The library shall provide an API to create test result objects programmatically."
            tests:
              - "TestOutcomeTests"

          - id: "REQ-FUNC-004"
            title: >-
              The library shall support standard test outcomes
              (Passed, Failed, Skipped, Inconclusive, NotExecuted).
            tests:
              - "TestOutcomeTests"

      - title: "Quality Requirements"
        requirements:
          - id: "REQ-QUAL-001"
            title: "The library shall have no external runtime dependencies."
            tests:
              - "DependencyTests"

          - id: "REQ-QUAL-002"
            title: "The library shall support .NET 8, 9, and 10."
            tests:
              - "FrameworkTests"

          - id: "REQ-QUAL-003"
            title: "The library shall provide strongly-typed C# objects for all test result structures."
            tests:
              - "TypeSafetyTests"

          - id: "REQ-QUAL-004"
            title: "The library shall build with zero compiler and analyzer warnings."
            tests:
              - "BuildTests"

      - title: "Documentation Requirements"
        requirements:
          - id: "REQ-DOC-001"
            title: "All public APIs shall have XML documentation comments."
            tests:
              - "DocumentationTests"

          - id: "REQ-DOC-002"
            title: "The library shall provide usage examples in the documentation."
            tests:
              - "ExampleTests"
